;;; ewm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ewm.el

(autoload 'ewm-down "ewm" "\
Navigate down, split window, or cycle buffers in monocle mode." t)
(autoload 'ewm-up "ewm" "\
Navigate up, split window, or cycle buffers in monocle mode." t)
(autoload 'ewm-left "ewm" "\
Split vertically or resize window based on current layout." t)
(autoload 'ewm-right "ewm" "\
Split vertically and move right, or resize window based on current layout." t)
(autoload 'ewm-delete-window "ewm" "\
Delete the current window, or kill the buffer if it's the only window." t)
(autoload 'ewm-swap-with-next-window "ewm" "\
Swap current window with next window." t)
(autoload 'ewm-swap-with-prev-window "ewm" "\
Swap current window with previous window." t)
(autoload 'ewm-monocle "ewm" "\
Toggle between multiple windows and single window (monocle mode).
This maximizes the current window while preserving the layout for restoration." t)
(autoload 'ewm-mode "ewm" "\
Minor mode for window management utilities.

Provides tiling window manager-style keybindings for window operations.

This is a minor mode.  If called interactively, toggle the `EWM mode'
mode.  If the prefix argument is positive, enable the mode, and if it is
zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `ewm-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-ewm-mode 'globalized-minor-mode t)
(defvar global-ewm-mode nil "\
Non-nil if Global Ewm mode is enabled.
See the `global-ewm-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-ewm-mode'.")
(custom-autoload 'global-ewm-mode "ewm" nil)
(autoload 'global-ewm-mode "ewm" "\
Toggle Ewm mode in all buffers.
With prefix ARG, enable Global Ewm mode if ARG is positive; otherwise,
disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Ewm mode is enabled in all buffers where `(lambda nil (ewm-mode 1))'
would do it.

See `ewm-mode' for more information on Ewm mode.

(fn &optional ARG)" t)
(register-definition-prefixes "ewm" '("ewm-"))

;;; End of scraped data

(provide 'ewm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ewm-autoloads.el ends here
